// Dependency-free interaction smoke test: a minimal DOM adapter, not browser visual QA.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
class Element{
 constructor(id=''){this.id=id;this.dataset={};this.handlers={};this.classList={add(){},remove(){}};this.style={};this.isConnected=true;this.innerHTML='';this.value='';this.tagName='DIV'}
 addEventListener(n,f){this.handlers[n]=f}setAttribute(k,v){this[k]=v}showModal(){this.open=true}close(){this.open=false}focus(){context.document.activeElement=this}scrollIntoView(){}querySelectorAll(){return[]}querySelector(){return null}
}
const nodes={};const get=id=>nodes[id]??(nodes[id]=new Element(id));
const timers=new Map();let timerId=0;const listeners={};const context={document:{getElementById:get,querySelector:()=>get('progress'),querySelectorAll:()=>[],activeElement:new Element(),body:new Element(),documentElement:{scrollHeight:1000}},window:{},location:{pathname:'/',search:'',hash:''},history:{pushState(a,b,p){context.location.hash=p.includes('#')?'#'+p.split('#')[1]:''},replaceState(a,b,p){this.pushState(a,b,p)}},URLSearchParams,innerHeight:800,scrollY:0,addEventListener(){},requestAnimationFrame:f=>f(),matchMedia:()=>({matches:true}),clearTimeout(id){timers.delete(id)},setTimeout(callback){const id=++timerId;timers.set(id,callback);return id},console};context.window.addEventListener=(n,f)=>listeners[n]=f;
vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/dist/data.js','utf8'),context);vm.runInContext(fs.readFileSync(root+'/dist/app.js','utf8'),context);
const data=context.window.MUSEUM_CASES;assert.equal(data.length,277);assert.equal(new Set(data.map(c=>c.source_index)).size,277);assert.equal(new Set(data.map(c=>c.id)).size,277);
get('search').handlers.input({isComposing:false});const compositionTimer=vm.runInContext('searchTimer',context);get('search').handlers.compositionstart();assert(!timers.has(compositionTimer),'Composition start should cancel a pending search');get('search').handlers.input({isComposing:true});assert.equal(timers.size,0,'Composing input should not leave a search timer queued');
const styles=fs.readFileSync(root+'/dist/style.css','utf8');assert(styles.includes('.reveal.visible'),'Scroll reveal classes should have visible styles');
const accents=[...styles.matchAll(/--color-orange:\s*(#[0-9a-f]{6})/gi)].map(([,color])=>color);const luminance=hex=>hex.match(/[0-9a-f]{2}/gi).map(value=>parseInt(value,16)/255).map(value=>value<=0.04045?value/12.92:((value+0.055)/1.055)**2.4).reduce((sum,value,index)=>sum+value*[0.2126,0.7152,0.0722][index],0);const contrast=(first,second)=>{const values=[luminance(first),luminance(second)].sort((a,b)=>b-a);return (values[0]+0.05)/(values[1]+0.05)};const accent=accents.at(-1);assert(accent,'Theme should define an orange accent');assert(contrast(accent,'#f3f1e9')>=4.5,'Accent text should meet WCAG AA on ivory');assert(contrast('#f9f7f7',accent)>=4.5,'White text should meet WCAG AA on accent buttons');
let shortcutPrevented=false;listeners.keydown({key:'k',metaKey:true,target:get('gallery'),preventDefault(){shortcutPrevented=true}});assert(shortcutPrevented);assert.equal(context.document.activeElement,get('search'));
let editableShortcutPrevented=false;listeners.keydown({key:'k',ctrlKey:true,target:{tagName:'INPUT'},preventDefault(){editableShortcutPrevented=true}});assert.equal(editableShortcutPrevented,false);
vm.runInContext('scrollY=-20;progress()',context);assert.equal(get('progress').style.transform,'scaleX(0)');vm.runInContext('scrollY=2000;progress()',context);assert.equal(get('progress').style.transform,'scaleX(1)');vm.runInContext('scrollY=0;progress()',context);
assert.equal(data.filter(c=>c.preview_status==='recovered-web').length,12);assert(data.every(c=>c.asset));
const originalUrls=new Map([[1,'https://inspiring.nk.studio/'],[2,'https://showcase.noomoagency.com/?ref=muzli_c79abc36'],[3,'https://www.studioloop.com.br/'],[4,'https://brik.space/type-yellow?utm_source=muzli&utm_medium=paid&utm_campaign=pa_media_buying_brik_8_26_organic&utm_content=tumble-brief-mix&utm_keep_original=true'],[5,'https://webgl-drum-machine.vercel.app/?ref=muzli_99fd0145'],[6,'https://heronaiapp.com/'],[7,'https://www.butter.video/'],[8,'https://brand.rocket.com/'],[9,'https://www.behance.net/gallery/242098083/-Rams-System-Icons'],[10,'https://www.mathis-biabiany.fr/?ref=muzli_2bf45231'],[11,'https://www.reimaginegenesis.com/'],[12,'https://verostudio.com/']]);
for(const [id,url] of originalUrls)assert.equal(data.find(c=>c.id===id)?.url,url,`Preserve original deep-link identity for case ${id}`);
assert.equal((get('gallery').innerHTML.match(/<article/g)||[]).length,24);
assert(get('gallery').innerHTML.includes('<a class="card-trigger" href="#case=1"'),'Case cards should be direct deep links');
const cardImages=[...get('gallery').innerHTML.matchAll(/<img\b[^>]*>/g)].map(([tag])=>tag);assert.equal(cardImages.length,24);assert(cardImages[0].includes('fetchpriority="high"'),'Prioritize the first exhibit preview');assert(cardImages.every(tag=>/\bwidth="\d+"/.test(tag)&&/\bheight="\d+"/.test(tag)),'Reserve preview dimensions to prevent layout shifts');assert(cardImages.slice(3).every(tag=>tag.includes('loading="lazy"')),'Lazy-load previews below the first three cards');
assert(get('gallery').innerHTML.includes('transition-delay:120ms'),'Scroll reveals should stagger visible cards');
get('detail').open=false;
for(const modifier of [{metaKey:true},{ctrlKey:true},{shiftKey:true},{altKey:true},{button:1}]){let prevented=false;const link={dataset:{id:'1'}};const hash=context.location.hash;get('gallery').handlers.click({target:{closest:selector=>selector==='[data-id]'?link:null},defaultPrevented:false,button:modifier.button||0,metaKey:!!modifier.metaKey,ctrlKey:!!modifier.ctrlKey,shiftKey:!!modifier.shiftKey,altKey:!!modifier.altKey,preventDefault(){prevented=true}});assert.equal(prevented,false,'Modified case activation should retain native link behavior');assert.equal(get('detail').open,false);assert.equal(context.location.hash,hash)}
const allPageIds=[];
for(let p=1;p<=12;p++){vm.runInContext(`page=${p};render()`,context);allPageIds.push(...[...get('gallery').innerHTML.matchAll(/data-id="(\d+)"/g)].map(m=>Number(m[1])))}
assert.equal(allPageIds.length,277);assert.equal(new Set(allPageIds).size,277);assert.equal(allPageIds.at(-1),277);assert.equal((get('gallery').innerHTML.match(/<article/g)||[]).length,13);
for(const category of ['沉浸體驗','品牌敘事','字體實驗','產品介面','視覺藝術','設計閱讀']){get('filters').handlers.click({target:{closest:()=>({dataset:{filter:category}})}});const count=vm.runInContext('filtered().length',context);assert.equal(count,data.filter(c=>c.category===category).length)}
vm.runInContext("category='全部';query='';page=1;render()",context);
for(const c of data){vm.runInContext(`showCase(${c.id})`,context);const body=get('detail-body').innerHTML;assert(body.includes(c.preview_status==='missing-in-source'?'原附件未保存預覽':c.asset),c.name);assert(body.includes('id="detail-title" aria-live="polite" aria-atomic="true"'),c.name+' should announce when the active exhibit changes');assert(!body.includes('undefined'),c.name);assert(body.includes(`第 ${c.pdf_page} 頁`));if(c.preview_status==='recovered-web'){assert(body.includes(c.preview_source_label));assert(body.includes(c.preview_retrieved_at));assert(!body.includes('原附件未保存預覽'));}}
assert.equal(get('next').disabled,true);get('prev').onclick();assert(get('detail-number').textContent.includes('276'));get('detail').handlers.cancel({preventDefault(){}});assert.equal(get('detail').open,false);vm.runInContext('page=1;render()',context);const clickTrigger=new Element('case-trigger');clickTrigger.dataset.id='1';context.document.activeElement=context.document.body;context.showCase(1,clickTrigger);context.clickTrigger=clickTrigger;assert(vm.runInContext('lastTrigger===clickTrigger',context));context.closeDetail();assert.equal(context.document.activeElement,clickTrigger,'Restore the clicked card even when the browser did not focus it before opening the dialog');
get('search').value='Rams';get('search-form').handlers.submit({preventDefault(){}});assert.equal(vm.runInContext('filtered().length',context),1);assert(get('gallery').innerHTML.includes('Rams System Icons'));
get('search').value='明度差';get('search-form').handlers.submit({preventDefault(){}});assert(vm.runInContext('filtered().some(c=>c.id===1)',context),'Search should include curator observations');
get('search').value='zzzz_no_match_641';get('search-form').handlers.submit({preventDefault(){}});assert(get('gallery').innerHTML.includes('清除搜尋與分類'));assert.equal(get('pagination').hidden,true);assert.equal(get('page-caption').textContent,'','No-results state should not claim all 277 cases are visible');
get('gallery').handlers.click({target:{closest:s=>s==='#reset-results'?{}:null}});assert.equal(vm.runInContext('filtered().length',context),277);
context.document.activeElement=context.document.body;context.location.hash='#case=277';listeners.popstate();assert.equal(get('detail').open,true);assert(get('detail-body').innerHTML.includes('DES'));assert.equal(vm.runInContext('page',context),12);
context.location.hash='#category='+encodeURIComponent('產品介面')+'&q=Rams';listeners.popstate();assert.equal(get('detail').open,false);assert(get('gallery').innerHTML.includes('Rams System Icons'));assert.equal(context.document.activeElement,get('collection-title'),'Restore focus after browser-history closes a deep-linked detail');
context.document.activeElement=context.document.body;context.location.hash='#case=277';listeners.popstate();get('close').onclick();assert.equal(context.document.activeElement,get('collection-title'),'Closing a direct deep link should focus the collection heading');assert.equal(context.location.hash,'#page=12');
context.location.hash='#page=999999';listeners.popstate();assert.equal(vm.runInContext('page',context),12);get('gallery').innerHTML='duplicate-state-sentinel';listeners.hashchange();assert.equal(get('gallery').innerHTML,'duplicate-state-sentinel','Ignore duplicate hashchange after popstate');
for(const c of data){assert(/^https?:\/\//i.test(c.url),'Valid exhibit URL: '+c.name);assert(/^https?:\/\//i.test(c.source_url),'Valid source URL: '+c.name);if(c.preview_source_url)assert(/^https?:\/\//i.test(c.preview_source_url),'Valid recovered preview URL: '+c.name);if(c.asset){assert(fs.existsSync(root+'/dist/'+c.asset));assert(Number.isInteger(c.width)&&c.width>0&&Number.isInteger(c.height)&&c.height>0,'Valid preview dimensions: '+c.name)}assert(c.analysis&&c.lesson&&c.summary&&c.headline&&c.tags.length)}
console.log('PASS: 277 unique source records; original 12 IDs preserved; 12 pages without omissions or repeats; six category totals; every detail/preview/source page; missing-image state; search and no results; deep links and browser-history restoration; navigation boundaries.');
